/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as MultiRouteImport } from './routes/multi'
import { Route as BrainstormRouteImport } from './routes/brainstorm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces.index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows.index'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces.$workspaceId'
import { Route as WorkflowsWorkflowIdRouteImport } from './routes/workflows.$workflowId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiRoute = MultiRouteImport.update({
  id: '/multi',
  path: '/multi',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainstormRoute = BrainstormRouteImport.update({
  id: '/brainstorm',
  path: '/brainstorm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacesRoute,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => WorkspacesRoute,
} as any)
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: '/$workflowId',
  path: '/$workflowId',
  getParentRoute: () => WorkflowsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brainstorm': typeof BrainstormRoute
  '/multi': typeof MultiRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brainstorm': typeof BrainstormRoute
  '/multi': typeof MultiRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/workspaces': typeof WorkspacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brainstorm': typeof BrainstormRoute
  '/multi': typeof MultiRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brainstorm'
    | '/multi'
    | '/workflows'
    | '/workspaces'
    | '/projects/$projectId'
    | '/workflows/$workflowId'
    | '/workspaces/$workspaceId'
    | '/workflows/'
    | '/workspaces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brainstorm'
    | '/multi'
    | '/projects/$projectId'
    | '/workflows/$workflowId'
    | '/workspaces/$workspaceId'
    | '/workflows'
    | '/workspaces'
  id:
    | '__root__'
    | '/'
    | '/brainstorm'
    | '/multi'
    | '/workflows'
    | '/workspaces'
    | '/projects/$projectId'
    | '/workflows/$workflowId'
    | '/workspaces/$workspaceId'
    | '/workflows/'
    | '/workspaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrainstormRoute: typeof BrainstormRoute
  MultiRoute: typeof MultiRoute
  WorkflowsRoute: typeof WorkflowsRouteWithChildren
  WorkspacesRoute: typeof WorkspacesRouteWithChildren
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi': {
      id: '/multi'
      path: '/multi'
      fullPath: '/multi'
      preLoaderRoute: typeof MultiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brainstorm': {
      id: '/brainstorm'
      path: '/brainstorm'
      fullPath: '/brainstorm'
      preLoaderRoute: typeof BrainstormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkflowsRouteChildren {
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

const WorkflowsRouteChildren: WorkflowsRouteChildren = {
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}

const WorkflowsRouteWithChildren = WorkflowsRoute._addFileChildren(
  WorkflowsRouteChildren,
)

interface WorkspacesRouteChildren {
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

const WorkspacesRouteChildren: WorkspacesRouteChildren = {
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}

const WorkspacesRouteWithChildren = WorkspacesRoute._addFileChildren(
  WorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrainstormRoute: BrainstormRoute,
  MultiRoute: MultiRoute,
  WorkflowsRoute: WorkflowsRouteWithChildren,
  WorkspacesRoute: WorkspacesRouteWithChildren,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
